CREATE TABLE BOOKENTITY
(
  ID     BIGINT PRIMARY KEY NOT NULL IDENTITY,
  AUTHOR VARCHAR(255)       NOT NULL,
  TITLE  VARCHAR(255)       NOT NULL
);
CREATE UNIQUE INDEX SYS_IDX_UK_NEN4J5JU6WUIIX5AXQ6W2XBWM_10099
  ON BOOKENTITY (TITLE);

-- =====================================

INSERT INTO BOOKENTITY VALUES('1','1TITLE', '1AUTHOR');
INSERT INTO BOOKENTITY VALUES('2','2TITLE', '2AUTHOR');
INSERT INTO BOOKENTITY VALUES('3','3TITLE', '3AUTHOR');
INSERT INTO BOOKENTITY VALUES('4','4TITLE', '4AUTHOR');
INSERT INTO BOOKENTITY VALUES('5','5TITLE', '5AUTHOR');
INSERT INTO BOOKENTITY VALUES('6','6TITLE', '6AUTHOR');
INSERT INTO BOOKENTITY VALUES('7','7TITLE', '7AUTHOR');

--============================================================
CREATE TABLE BOOKENTITY_TEST
(
  ID     BIGINT PRIMARY KEY NOT NULL IDENTITY,
  AUTHOR VARCHAR(255)       NOT NULL,
  TITLE  VARCHAR(255)       NOT NULL
);
-- CREATE UNIQUE INDEX SYS_IDX_UK_10099
--   ON BOOKENTITY_TEST (TITLE);

-- =====================================

INSERT INTO BOOKENTITY_TEST VALUES('1','1TITLE', '1AUTHOR');
INSERT INTO BOOKENTITY_TEST VALUES('2','2TITLE', '2AUTHOR');
INSERT INTO BOOKENTITY_TEST VALUES('3','3TITLE', '3AUTHOR');
INSERT INTO BOOKENTITY_TEST VALUES('4','4TITLE', '4AUTHOR');
INSERT INTO BOOKENTITY_TEST VALUES('5','5TITLE', '5AUTHOR');
INSERT INTO BOOKENTITY_TEST VALUES('6','6TITLE', '6AUTHOR');
INSERT INTO BOOKENTITY_TEST VALUES('7','7TITLE', '7AUTHOR');

